name: Publish Release
concurrency: publish
on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm run build-package
      - name: create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
          tag_name: ${{ github.event.inputs.tags }}
